# Generated by Django 4.0 on 2022-10-13 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0003_calendar_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quitplan',
            name='days_passed',
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='start_day',
            field=models.DateField(default=datetime.date(2022, 10, 13)),
        ),
    ]
