# Generated by Django 4.0 on 2022-10-14 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0004_remove_quitplan_days_passed_alter_quitplan_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='start_day',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
