# Generated by Django 4.1.1 on 2022-10-16 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0005_alter_forum_date_posted_alter_quitplan_start_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='planid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='start_day',
            field=models.DateField(default=datetime.date(2022, 10, 17)),
        ),
    ]
