# Generated by Django 4.0 on 2022-10-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0006_alter_forum_date_posted_alter_quitplan_planid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tot_plan',
        ),
    ]
