# Generated by Django 4.0 on 2022-10-18 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0008_alter_forum_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='planid',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AlterField(
            model_name='quitplan',
            name='start_day',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
    ]
