# Generated by Django 4.1.1 on 2022-10-18 14:51

import django.contrib.postgres.fields
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0009_calendar_planid_alter_forum_date_posted_and_more'),
    ]

    operations = [
        HStoreExtension(),

    ]
