# Generated by Django 4.1.1 on 2022-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0011_calendar_datearray_alter_calendar_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='datearray',
        ),
    ]
