# Generated by Django 4.1.1 on 2022-10-18 14:58

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0012_remove_calendar_datearray'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='datearray',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
