# Generated by Django 4.1.1 on 2022-10-18 15:39

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0013_calendar_datearray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datearray',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'': ''}),
        ),
    ]
