# Generated by Django 4.1.1 on 2022-10-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0015_alter_calendar_userid_alter_forum_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quitplan',
            name='planid',
            field=models.IntegerField(),
        ),
    ]
