# Generated by Django 4.1.1 on 2022-10-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitnow', '0016_alter_quitplan_planid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='date',
        ),
    ]
